name: bgm-agit-front

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: SCP dist folder to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: '22'
          source: dist/*
          target: /home/ubuntu/deploy/front-dist-temp

      - name: SSH로 실제 경로에 덮어쓰기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: '22'
          script_stop: true
          script: |
            sudo rm -rf /usr/share/nginx/bgmagit-front/dist
            sudo mv /home/ubuntu/deploy/front-dist-temp/* /usr/share/nginx/bgmagit-front/
            sudo systemctl restart nginx